version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - main.env
    networks:
      - app-network
    depends_on:
      - db
    command: npm run dev

  frontend:
    image: node:latest
    working_dir: /app
    command: sh -c "npm install && npm start"
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    env_file:
      - main.env
    stdin_open: true
    tty: true
    networks:
      - app-network

  db:
    image: postgres:16
    env_file:
      - main.env
    ports:
      - "5432:5432"
    volumes:
      - db07-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db07-data:

networks:
  app-network:
    driver: bridge