version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    image: node:latest  # Use the official node image
    working_dir: /app  # Set working directory
    command: sh -c "npm install && npm start"  # Install dependencies and start CRA server
    volumes:
      - ./client:/app  # Mount the local source code to the container
      - /app/node_modules  # Avoid overwriting node_modules from the container
    ports:
      - "3000:3000"  # CRA runs on port 3000 by default
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for hot reloading
    stdin_open: true  # Keep the container running
    tty: true  # Allocate a pseudo-TTY
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: usermanager
      POSTGRES_PASSWORD: 4usermanager2play
    ports:
      - "5432:5432"
    volumes:
      - dbt1-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  dbt1-data:

networks:
  app-network:
    driver: bridge
