version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: usermanager
      POSTGRES_PASSWORD: 4usermanager2play
    ports:
      - "5432:5432"
    volumes:
      - db1-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db1-data:

networks:
  app-network:
    driver: bridge
